export enum Routes {
  MAIN = 'main',
  ABOUT = 'about',
  CATALOG = 'catalog',
  LOOK_CONSTRUCTOR = 'look_constructor',
  SELLER = 'seller',
  SHOPS = 'shops',
  SHOP = 'shop',
  CHOSEN_LOOK = 'chosen_look',
  TOTAL_LOOK_CATALOG = 'total_look_catalog',
  TOTAL_LOOK = 'total_look',
  COLLECTIONS = 'collections',
  COLLECTIONS_CATALOG = 'collections_catalog',
  PRODUCT = 'product',
  BLOG = 'blog',
  POST = 'post',
  VACANCY = 'vacancy',
  SEARCH = 'search',
  CHECKOUT = 'checkout',
  OFFICE = 'office',
  OFFICE_MENU = 'office_menu',
  OFFICE_ORDERS = 'office_orders',
  OFFICE_REVIEWS = 'office_reviews',
  OFFICE_VIEWED = 'office_viewed',
  OFFICE_WISHLIST = 'office_wishlist',
  OFFICE_BONUSES = 'office_bonuses',
  OFFICE_CONSULTATIONS = 'office_consultations',
  OFFICE_FEEDBACK = 'office_feedback',
  SIZES = 'sizes',
  CONTACTS = 'contacts',
  BONUSES = 'bonuses',
  CERTIFICATES = 'certificates',
  FAQ = 'faq',
  PROMOTIONS = 'promotions',
  SALE = 'sale',
  LOGOUT = 'logout',
  CHECKOUT_SUCCESS = 'checkout_success',
  INSTAGRAM = 'instagram',
  NEW_ARRIVALS = 'new_arrivals',
  NOT_FOUND = 'not_found',
}

export const routerPaths = {
  [Routes.MAIN]: '/',
  [Routes.ABOUT]: '/about',
  [Routes.CATALOG]: '/catalog',
  [Routes.CHECKOUT]: '/checkout',
  [Routes.LOOK_CONSTRUCTOR]: '/look-constructor',
  [Routes.CHOSEN_LOOK]: '/chosen-look',
  [Routes.SELLER]: (sellerId: string) => `/staff/${sellerId}`,
  [Routes.SHOPS]: '/stores',
  [Routes.VACANCY]: '/vacancies',
  [Routes.SEARCH]: '/search',
  [Routes.OFFICE]: '/office',
  [Routes.OFFICE_MENU]: '/office/menu',
  [Routes.OFFICE_ORDERS]: '/office/orders',
  [Routes.OFFICE_REVIEWS]: '/office/reviews',
  [Routes.OFFICE_VIEWED]: '/office/viewed',
  [Routes.OFFICE_WISHLIST]: '/office/wish-list',
  [Routes.OFFICE_BONUSES]: '/office/bonuses',
  [Routes.OFFICE_CONSULTATIONS]: '/office/consultations',
  [Routes.OFFICE_FEEDBACK]: '/office/feedback',
  [Routes.LOGOUT]: '/logout',
  [Routes.SIZES]: '/sizes',
  [Routes.CONTACTS]: '/contacts',
  [Routes.BONUSES]: '/bonuses',
  [Routes.CERTIFICATES]: '/certificates',
  [Routes.INSTAGRAM]: '/instagram',
  [Routes.FAQ]: '/faq',
  [Routes.PROMOTIONS]: '/promotions',
  [Routes.SALE]: '/catalog/sale',
  [Routes.NEW_ARRIVALS]: '/catalog/new',
  [Routes.CHECKOUT_SUCCESS]: (orderId: string) => `/checkout-success?order_id=${orderId}`,
  [Routes.POST]: (slug: string) => `/post/${slug}`,
  [Routes.BLOG]: (slug?: string) => `/blog${slug ? `/${slug}` : ''}`,
  [Routes.SHOP]: (shopId: string) => `/stores/${shopId}`,
  [Routes.COLLECTIONS]: (gender?: string) => `/collections${gender ? `/${gender}` : ''}`,
  [Routes.COLLECTIONS_CATALOG]: (collectionId: string) => `/collection/${collectionId}`,
  [Routes.TOTAL_LOOK_CATALOG]: (gender?: string) => `/looks${gender ? `/${gender}` : ''}`,
  [Routes.TOTAL_LOOK]: (id: string) => `/looks/${id}`,
  [Routes.PRODUCT]: (slug: string) => `/product/${slug}`,
  [Routes.NOT_FOUND]: '/404',
} as const;
